name: "End-to-End Tests"
on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        default: "8.0.x"
        description: ".NET SDK version to use"
      test-name:
        type: string
        default: "End-to-End Tests"
        description: "Name for the test job (e.g., 'End-to-End Tests')"
      artifact-name:
        type: string
        default: "build-output"
        description: "Name of the build artifact to download."
      collect-coverage:
        type: boolean
        default: false
        description: "Whether to collect and upload code coverage."
      test-filter:
        type: string
        default: "Category=E2E|FullyQualifiedName~E2E.Tests"
        description: "Filter for selecting which tests to run."
      test-project-path:
        type: string
        default: "path/to/your/E2E-tests"
        description: "Path to the E2E test project directory."

jobs:
  e2e-tests:
    uses: "./.github/workflows/playwright-test-runner.yml"
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
      test-name: ${{ inputs.test-name }}
      test-filter: ${{ inputs.test-filter }}
      artifact-name: ${{ inputs.artifact-name }}
      collect-coverage: ${{ inputs.collect-coverage }}
      test-project-path: ${{ inputs.test-project-path }}
