name: "Healthcheck - cURL Endpoint Check"
on:
  workflow_call:
    inputs:
      base-url:
        description: "Base URL to test"
        type: string
        required: true
      routes:
        description: "JSON array of routes to test"
        type: string
        required: true
      timeout:
        description: "Request timeout in seconds"
        type: number
        required: false
        default: 30
      retries:
        description: "Number of retries per endpoint"
        type: number
        required: false
        default: 5
      retry-delay:
        description: "Delay between retries in seconds"
        type: number
        required: false
        default: 5

jobs:
  healthcheck:
    name: "Healthcheck Endpoints"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test endpoints"
        env:
          BASE_URL: "${{ inputs.base-url }}"
          ROUTES_ARRAY: "${{ inputs.routes }}"
          MAX_TIMEOUT: ${{ inputs.timeout }}
          RETRY_ATTEMPTS: ${{ inputs.retries }}
          RETRY_DELAY: ${{ inputs.retry-delay }}
        run: |
          set -euo pipefail

          # Parse JSON routes array into bash array
          readarray -t ROUTES < <(echo "$ROUTES_ARRAY" | jq -r '.[]')

          echo "Testing endpoints at: $BASE_URL"
            failed_routes=()
            
            for route in "${ROUTES[@]}"; do
              FULL_URL="${BASE_URL}${route}"
              
              if curl -fsS \
                --max-time "$MAX_TIMEOUT" \
                --retry "$RETRY_ATTEMPTS" \
                --retry-all-errors \
                --retry-delay "$RETRY_DELAY" \
                -o /dev/null \
                "$FULL_URL"; then
                echo "✓ $FULL_URL is responding"
              else
                echo "✗ $FULL_URL failed"
                failed_routes+=("$FULL_URL")
              fi
            done
            
            if [ ${#failed_routes[@]} -gt 0 ]; then
              echo ""
              echo "❌ ${#failed_routes[@]} endpoint(s) failed:"
              printf '  - %s\n' "${failed_routes[@]}"
              exit 1
            fi
            
            echo "✅ All endpoints are responding"