name: "OpenTofu Build Infrastructure"

on:
  workflow_call:
    inputs:
      opentofu-version:
        required: false
        type: string
        default: "1.10.5"
      infrastructure-directory:
        required: false
        type: string
        default: "./infrastructure"
      environment:
        required: false
        type: string
        default: "default"
      retention-days:
        required: false
        type: number
        default: 1
    secrets:
      AZURE_CREDENTIALS:
        description: |
          A JSON object containing Azure Service Principal credentials.
          {
            "clientId": "********",
            "clientSecret": "********",
            "subscriptionId": "********",
            "tenantId": "********"
          }
        required: true
    outputs:
      tofu-outputs:
        description: "A JSON string containing all OpenTofu outputs."
        value: ${{ jobs.opentofu-apply.outputs.tofu-outputs }}

jobs:
  opentofu-plan:
    name: "OpenTofu Plan"
    runs-on: "ubuntu-latest"
    outputs:
      plan-exitcode: ${{ steps.plan.outputs.exitcode }}
      plan-text: ${{ steps.plan.outputs.plan_text }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup OpenTofu"
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.opentofu-version }}
          tofu_wrapper: false

      - name: "Azure CLI Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Cache OpenTofu providers"
        uses: actions/cache@v4
        with:
          path: ${{ inputs.infrastructure-directory }}/.terraform
          key: ${{ runner.os }}-tofu-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.infrastructure-directory)) }}
          restore-keys: |
            ${{ runner.os }}-tofu-

      - name: "OpenTofu Init"
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu init

      - name: "Select OpenTofu Workspace"
        if: inputs.environment != ''
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu workspace select ${{ inputs.environment }} || tofu workspace new ${{ inputs.environment }}

      - name: "OpenTofu Validate"
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu validate

      - name: "OpenTofu Plan"
        id: plan
        working-directory: ${{ inputs.infrastructure-directory }}
        run: |
          tofu plan -detailed-exitcode -no-color -out=tfplan > plan.txt
          exit_code=$?
          echo "exitcode=${exit_code}" >> $GITHUB_OUTPUT
          
          delimiter=$(uuidgen)
          echo "plan_text<<$delimiter" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

          if [ "${exit_code}" -eq 1 ]; then
            cat plan.txt
            exit 1
          fi

          # Always exit 0 unless there was a real error
          exit 0

      - name: "Upload OpenTofu Plan"
        uses: actions/upload-artifact@v4
        with:
          name: "opentofu-plan-${{ inputs.environment || 'default' }}-${{ github.run_id }}"
          path: ${{ inputs.infrastructure-directory }}/tfplan
          retention-days: ${{ inputs.retention-days }}

  opentofu-apply:
    needs: [ "opentofu-plan" ]
    name: "OpenTofu Apply"
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    outputs:
      tofu-outputs: ${{ steps.outputs.outputs.json }}
    steps:
      - name: "Show Plan Output"
        run: |
          echo "--- OpenTofu Plan Text Output ---"
          echo "${{ needs.opentofu-plan.outputs.plan-text }}"
          echo "---------------------------------"

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup OpenTofu"
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.opentofu-version }}
          tofu_wrapper: false

      - name: "Azure CLI Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Cache OpenTofu providers"
        uses: actions/cache@v4
        with:
          path: ${{ inputs.infrastructure-directory }}/.terraform
          key: ${{ runner.os }}-tofu-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.infrastructure-directory)) }}
          restore-keys: |
            ${{ runner.os }}-tofu-

      - name: "Download OpenTofu Plan"
        if: needs.opentofu-plan.outputs.plan-exitcode == 2
        uses: actions/download-artifact@v4
        with:
          name: "opentofu-plan-${{ inputs.environment || 'default' }}-${{ github.run_id }}"
          path: ${{ inputs.infrastructure-directory }}

      - name: "OpenTofu Init"
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu init

      - name: "Select OpenTofu Workspace"
        if: inputs.environment != ''
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu workspace select ${{ inputs.environment }} || tofu workspace new ${{ inputs.environment }}

      - name: "OpenTofu Apply"
        if: needs.opentofu-plan.outputs.plan-exitcode == 2
        working-directory: ${{ inputs.infrastructure-directory }}
        run: tofu apply -auto-approve tfplan

      - name: "Show State"
        if: always()
        working-directory: ${{ inputs.infrastructure-directory }}
        run: |
          echo "--- OpenTofu State Inspection ---"
          tofu show
          echo "---------------------------------"

      - name: "Get OpenTofu Outputs"
        id: outputs
        working-directory: ${{ inputs.infrastructure-directory }}
        run: |
          echo "--- Debugging OpenTofu Outputs ---"
          output_keys=$(tofu output -json | jq -r 'keys_unsorted | @sh')
          for key in $output_keys; do
            value=$(tofu output -raw "${key//\'/}")
            echo "::add-mask::${value}"
            echo "Output '${key//\'/}': found with length ${#value}"
          done
          echo "-----------------------------------"

          delimiter=$(uuidgen)
          echo "json<<$delimiter" >> $GITHUB_OUTPUT
          tofu output -json >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT